grid_map_topic: /mapper/debug/gridmap
grid_map_visualizations:
    - name: occupancy_grid
      type: occupancy_grid
      params:
          layer: "probability"
          data_min: 0.0
          data_max: 1.0
