scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: flake8

pycodestyle:  # Same as scanner.linter value. Other option is flake8
    max-line-length: 120  # Default is 79 in PEP 8
