/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_NEW_SWERVE_COMMANDS_PB_H_INCLUDED
#define PB_NEW_SWERVE_COMMANDS_PB_H_INCLUDED
#include "../pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _NewRequestMessage { 
    bool has_fl_velocity;
    float fl_velocity; 
    bool has_fr_velocity;
    float fr_velocity; 
    bool has_bl_velocity;
    float bl_velocity; 
    bool has_br_velocity;
    float br_velocity; 
    bool has_fl_angle;
    float fl_angle; 
    bool has_fr_angle;
    float fr_angle; 
    bool has_bl_angle;
    float bl_angle; 
    bool has_br_angle;
    float br_angle; 
    bool has_duration;
    float duration; 
} NewRequestMessage;

typedef struct _NewResponseMessage { 
    bool has_fibResponse;
    uint32_t fibResponse; 
} NewResponseMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define NewResponseMessage_init_default          {false, 0}
#define NewRequestMessage_init_default           {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define NewResponseMessage_init_zero             {false, 0}
#define NewRequestMessage_init_zero              {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define NewRequestMessage_fl_velocity_tag        1
#define NewRequestMessage_fr_velocity_tag        2
#define NewRequestMessage_bl_velocity_tag        3
#define NewRequestMessage_br_velocity_tag        4
#define NewRequestMessage_fl_angle_tag           5
#define NewRequestMessage_fr_angle_tag           6
#define NewRequestMessage_bl_angle_tag           7
#define NewRequestMessage_br_angle_tag           8
#define NewRequestMessage_duration_tag           9
#define NewResponseMessage_fibResponse_tag       1

/* Struct field encoding specification for nanopb */
#define NewResponseMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   fibResponse,       1)
#define NewResponseMessage_CALLBACK NULL
#define NewResponseMessage_DEFAULT NULL

#define NewRequestMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    fl_velocity,       1) \
X(a, STATIC,   OPTIONAL, FLOAT,    fr_velocity,       2) \
X(a, STATIC,   OPTIONAL, FLOAT,    bl_velocity,       3) \
X(a, STATIC,   OPTIONAL, FLOAT,    br_velocity,       4) \
X(a, STATIC,   OPTIONAL, FLOAT,    fl_angle,          5) \
X(a, STATIC,   OPTIONAL, FLOAT,    fr_angle,          6) \
X(a, STATIC,   OPTIONAL, FLOAT,    bl_angle,          7) \
X(a, STATIC,   OPTIONAL, FLOAT,    br_angle,          8) \
X(a, STATIC,   OPTIONAL, FLOAT,    duration,          9)
#define NewRequestMessage_CALLBACK NULL
#define NewRequestMessage_DEFAULT NULL

extern const pb_msgdesc_t NewResponseMessage_msg;
extern const pb_msgdesc_t NewRequestMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define NewResponseMessage_fields &NewResponseMessage_msg
#define NewRequestMessage_fields &NewRequestMessage_msg

/* Maximum encoded size of messages (where known) */
#define NewRequestMessage_size                   45
#define NewResponseMessage_size                  6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
