/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_SWERVE_COMMANDS_PB_H_INCLUDED
#define PB_SWERVE_COMMANDS_PB_H_INCLUDED
#include "pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _RequestMessage { 
    bool has_buffer;
    float buffer;
    bool has_fl_velocity;
    float fl_velocity;
    bool has_fr_velocity;
    float fr_velocity;
    bool has_bl_velocity;
    float bl_velocity;
    bool has_br_velocity;
    float br_velocity;
    bool has_fl_angle;
    float fl_angle;
    bool has_fr_angle;
    float fr_angle;
    bool has_bl_angle;
    float bl_angle;
    bool has_br_angle;
    float br_angle;
    bool has_duration;
    float duration;
} RequestMessage;

typedef struct _ResponseMessage { 
    bool has_buffer;
    float buffer;
    bool has_fl_velocity_est;
    float fl_velocity_est;
    bool has_fr_velocity_est;
    float fr_velocity_est;
    bool has_bl_velocity_est;
    float bl_velocity_est;
    bool has_br_velocity_est;
    float br_velocity_est;
    bool has_fl_angle_est;
    float fl_angle_est;
    bool has_fr_angle_est;
    float fr_angle_est;
    bool has_bl_angle_est;
    float bl_angle_est;
    bool has_br_angle_est;
    float br_angle_est;
    bool has_duration;
    float duration;
} ResponseMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ResponseMessage_init_default             {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define RequestMessage_init_default              {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define ResponseMessage_init_zero                {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define RequestMessage_init_zero                 {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define RequestMessage_buffer_tag                1
#define RequestMessage_fl_velocity_tag           2
#define RequestMessage_fr_velocity_tag           3
#define RequestMessage_bl_velocity_tag           4
#define RequestMessage_br_velocity_tag           5
#define RequestMessage_fl_angle_tag              6
#define RequestMessage_fr_angle_tag              7
#define RequestMessage_bl_angle_tag              8
#define RequestMessage_br_angle_tag              9
#define RequestMessage_duration_tag              10
#define ResponseMessage_buffer_tag               1
#define ResponseMessage_fl_velocity_est_tag      2
#define ResponseMessage_fr_velocity_est_tag      3
#define ResponseMessage_bl_velocity_est_tag      4
#define ResponseMessage_br_velocity_est_tag      5
#define ResponseMessage_fl_angle_est_tag         6
#define ResponseMessage_fr_angle_est_tag         7
#define ResponseMessage_bl_angle_est_tag         8
#define ResponseMessage_br_angle_est_tag         9
#define ResponseMessage_duration_tag             10

/* Struct field encoding specification for nanopb */
#define ResponseMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    buffer,            1) \
X(a, STATIC,   OPTIONAL, FLOAT,    fl_velocity_est,   2) \
X(a, STATIC,   OPTIONAL, FLOAT,    fr_velocity_est,   3) \
X(a, STATIC,   OPTIONAL, FLOAT,    bl_velocity_est,   4) \
X(a, STATIC,   OPTIONAL, FLOAT,    br_velocity_est,   5) \
X(a, STATIC,   OPTIONAL, FLOAT,    fl_angle_est,      6) \
X(a, STATIC,   OPTIONAL, FLOAT,    fr_angle_est,      7) \
X(a, STATIC,   OPTIONAL, FLOAT,    bl_angle_est,      8) \
X(a, STATIC,   OPTIONAL, FLOAT,    br_angle_est,      9) \
X(a, STATIC,   OPTIONAL, FLOAT,    duration,         10)
#define ResponseMessage_CALLBACK NULL
#define ResponseMessage_DEFAULT NULL

#define RequestMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, FLOAT,    buffer,            1) \
X(a, STATIC,   OPTIONAL, FLOAT,    fl_velocity,       2) \
X(a, STATIC,   OPTIONAL, FLOAT,    fr_velocity,       3) \
X(a, STATIC,   OPTIONAL, FLOAT,    bl_velocity,       4) \
X(a, STATIC,   OPTIONAL, FLOAT,    br_velocity,       5) \
X(a, STATIC,   OPTIONAL, FLOAT,    fl_angle,          6) \
X(a, STATIC,   OPTIONAL, FLOAT,    fr_angle,          7) \
X(a, STATIC,   OPTIONAL, FLOAT,    bl_angle,          8) \
X(a, STATIC,   OPTIONAL, FLOAT,    br_angle,          9) \
X(a, STATIC,   OPTIONAL, FLOAT,    duration,         10)
#define RequestMessage_CALLBACK NULL
#define RequestMessage_DEFAULT NULL

extern const pb_msgdesc_t ResponseMessage_msg;
extern const pb_msgdesc_t RequestMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ResponseMessage_fields &ResponseMessage_msg
#define RequestMessage_fields &RequestMessage_msg

/* Maximum encoded size of messages (where known) */
#define RequestMessage_size                      50
#define ResponseMessage_size                     50

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
