#!/bin/bash


echo ""
echo "Creating: candi.pro"
shopt -s extglob 
echo $CFLAGS
qmake-qt4 -project \
		-o candi.pro \
		CONFIG+=debug \
		QT+=xml \
		QMAKE_CFLAGS+="-fopenmp" \
		QMAKE_CXXFLAGS+="-fopenmp" \
		QMAKE_LFLAGS+="-fopenmp" \
		LIBS+="-L /usr/local/lib -lltdl -lpthread -lm"  \
		LIBS+="-lGL" \
		LIBS+="-ldc1394" \
		LIBS+="-lglut" \
		LIBS+="-lcv -lcvaux -lhighgui	" \
		INCLUDEPATH+="/usr/include/opencv" \
		INCLUDEPATH+="/usr/local/include/opencv" \
		INCLUDEPATH+="/usr/include/qt4/Qt" \
		INCLUDEPATH+="../old_motors" \
		-after \
		`./_remove-sources logging/*.+(c|cc|cpp|h)` \



echo "Creating: Makefile"
qmake-qt4 -makefile

echo "Type 'make' to compile everything"
echo ""
