<?xml version="1.0"?>

<robot name="Swervi" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- makes shock for drive wheel -->
    <xacro:macro name="drive_shock" params="prefix x_pos y_pos">
        <joint name="${prefix}_drive_shock" type="prismatic">
            <parent link="base_link"/>
            <child link="${prefix}_swerve_base"/>
            <origin xyz="${x_pos} ${y_pos} ${wheel_radius+swivel_height}"
                    rpy="0 0 0"/>
            <axis xyz="0 0 -1"/>
            <limit lower="${-drive_wheel_travel / 2}" upper="${drive_wheel_travel / 2}"
                    effort="${drive_shock_eff_limit}" velocity="${drive_shock_vel_limit}"/>
            <dynamics damping="${drive_shock_damping}" friction="${drive_shock_friction}"
                        spring_stiffness="${drive_spring_stiffness}" spring_reference="${drive_shock_spring_ref}"/>
        </joint>
        <transmission name="${prefix}_drive_shock_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_drive_shock">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_drive_shock_act">
                <!-- This hardwareInterface element exists for compatibility
                    with ROS Hydro. -->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <!-- TODO parameterize to make consistent PID values work -->
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>
    </xacro:macro>

    <xacro:macro name="swerve_module" params="prefix x_pos y_pos">
        <link name="${prefix}_swerve_base">
            <xacro:null_link/>
        </link>

        <joint name="${prefix}_swivel_offset" type="fixed">
            <parent link="${prefix}_swerve_base"/>
            <child link="${prefix}_swivel_axle"/>
            <origin xyz="0 0 ${-swivel_height/2}" rpy="0 0 0"/>
        </joint>

        <link name="${prefix}_swivel_axle">
            <xacro:null_link/>
        </link>

        <joint name="${prefix}_swivel_rev" type="continuous">
            <parent link="${prefix}_swivel_axle"/>
            <child link="${prefix}_swerve_swivel"/>
            <axis xyz="0 0 -1"/>
            <limit effort="${max_torque_swivel}" velocity="${max_vel_swivel}"/>
            <dynamics damping="${swivel_damping}" friction="${swivel_friction}"/>
        </joint> 

        <link name="${prefix}_swerve_swivel">
            <visual>
                <geometry>
                    <cylinder length="${swivel_height}" radius="${swivel_radius}"/>
                </geometry>
            </visual>
            <inertial>
                <mass value="${swivel_mass}"/>
                <inertia ixx="${swivel_Ixx}" ixy="0.0" ixz="0.0" iyy="${swivel_Iyy}" iyz="0.0" izz="${swivel_Izz}"/>
            </inertial>
        </link>

        <transmission name="${prefix}_swivel_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_swivel_rev">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_swivel_act">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <joint name="${prefix}_wheel_offset" type="fixed">
            <parent link="${prefix}_swerve_swivel"/>
            <child link="${prefix}_wheel_axle"/>
            <origin xyz="0 0 ${-swivel_height/2}" rpy="0 0 0"/>
        </joint>

        <link name="${prefix}_wheel_axle">
            <xacro:null_link/>
        </link>

        <!-- The left and right axles have the same axis so that identical
         rotation values cause the wheels to rotate in the same direction. -->
        <joint name="${prefix}_wheel_axle" type="continuous">
            <parent link="${prefix}_wheel_axle"/>
            <child link="${prefix}_wheel"/>
            <origin xyz="0 0 0" rpy="${M_PI / 2} 0 0"/>
            <axis xyz="0 0 1"/>
            <limit effort="${max_torque_hub}" velocity="${max_vel_hub}"/>
            <dynamics damping="${wheel_damping}" friction="${wheel_friction}"/>
        </joint>

        <transmission name="${prefix}_axle_trans">
            <type>transmission_interface/SimpleTransmission</type>
            <joint name="${prefix}_wheel_axle">
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            </joint>
            <actuator name="${prefix}_axle_act">
                <!--This hardwareInterface element exists for compatibility
                    with ROS Hydro-->
                <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
                <mechanicalReduction>1</mechanicalReduction>
            </actuator>
        </transmission>

        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <mesh filename="package://igvc_description/urdf/meshes/swervi_tire.dae"/>
                </geometry>
            </visual>
            <collision>
                <geometry>
                    <mesh filename="package://igvc_description/urdf/meshes/swervi_tire.dae"/>
                </geometry>
                <max_contacts>10</max_contacts>
                <surface>
                    <contact>
                        <ode>
                            <soft_cfm>0.000000001</soft_cfm>
                            <soft_erp>0.2</soft_erp>
                            <kp>1e+10</kp>
                            <kd>10</kd>
                            <max_vel>0.01</max_vel>
                            <min_depth>0.005</min_depth>
                        </ode>
                    </contact>
                </surface>
            </collision>
            <inertial>
                <mass value="${wheel_mass}"/>
                <inertia  ixx="${wheel_Ixx_Iyy}"
                        ixy="0.0"
                        ixz="0.0"
                        iyy="${wheel_Ixx_Iyy}"
                        iyz="0.0"
                        izz="${wheel_Izz}" />
            </inertial>
        </link>

        <gazebo reference="${prefix}_wheel">
            <mu1>0.7</mu1>
            <mu2>0.75</mu2>
        </gazebo>

        <xacro:drive_shock prefix="${prefix}" x_pos="${x_pos}" y_pos="${y_pos}"/>
        
    </xacro:macro>
</robot>
