<?xml version="1.0"?>

<robot name="Swervi" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="swerve_module.urdf.xacro"/>

    <xacro:property name="wheel_diameter" value="0.275" />

    <!-- base of the robot, should be ground level, centered on the robot -->
    <link name="base_link">
        <xacro:null_link/>
    </link>

    <gazebo reference="base_link">
        <material>Gazebo/Grey</material>
    </gazebo>

    <link name="base_footprint">
        <xacro:null_link/>
    </link>

    <gazebo reference="base_footprint">
        <material>Gazebo/Grey</material>
    </gazebo>

    <joint name="base_footprint_to_base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0.0 0.0 ${wheel_diameter / 2}" rpy="0 0 0"/>
    </joint>

    <xacro:swerve_module prefix="tl" x_pos="0" y_pos="0"/> -->

    <!-- Just Used for testing -->
    <link name="world"/>
    <joint name="world_to_base_footprint" type="fixed">
        <parent link="world"/>
        <child link="base_footprint"/>
    </joint>

    <gazebo>
        <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
            <robotSimType>gazebo_ros_control/DefaultRobotHWSim</robotSimType>
        </plugin>

        <plugin name="p3d_base_controller" filename="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>200.0</updateRate>
            <bodyName>base_footprint</bodyName>
            <topicName>ground_truth/state_raw</topicName>
            <gaussianNoise>0.00</gaussianNoise>
            <frameName>world</frameName>
            <!-- origin is at spawn location -->
            <xyzOffset>0 0 0</xyzOffset>
            <rpyOffset>0 0 0</rpyOffset>
        </plugin>

    </gazebo>

</robot>