analyzers:
  imu:
    type: diagnostic_aggregator/GenericAnalyzer
    path: IMU
    startswith: 'imu'
    num_items: 2
  motors:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Motors
    contains: 'MC'
    num_items: 1
  battery:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Battery
    contains: 'Battery'
    num_items: 1
  controls:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Joystick
    contains: 'Joystick'
    num_items: 1
  lidar:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Lidar
    contains: 'lidar'
    num_items: 1