#!/bin/sh

echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"
echo "Ubuntu 8.10 only!"

echo "install libswscale"


# feel free to add to this script when you encounter missing libs/files
echo "installing candi dependencies this may take a while... =================="
echo "multiverse and universe repositories must be enabled! ==================="

sleep 1

echo "update =================================================================="
sudo apt-get update

echo "opencv dependencies======================================================="
sudo apt-get --yes install libgtk2.0-dev
sudo apt-get --yes install libavcodec-dev
sudo apt-get --yes install libavformat-dev
sudo apt-get --yes install libjpeg62-dev
sudo apt-get --yes install libtiff4-dev

echo "opencv =================================================================="
sudo apt-get --yes install libcv1
sudo apt-get --yes install libcvaux1 
sudo apt-get --yes install libhighgui1
sudo apt-get --yes install libcv-dev

echo "QT ======================================================================"
sudo apt-get --yes install libqt4-core
sudo apt-get --yes install libqt4-xml 
sudo apt-get --yes install libqt4-dev
sudo apt-get --yes install qt4-dev-tools

echo "boost ==================================================================="
sudo apt-get --yes install libboost1.35-dev	#ubuntu 8.10
#sudo apt-get --yes install libboost-dev		#ubuntu 8.04

echo "glut ====================================================================" 
sudo apt-get --yes install libglut-dev

echo "libtool ================================================================="
sudo apt-get --yes install libtool
sudo apt-get --yes install libmcrypt-dev

echo "g++ ====================================================================="
sudo apt-get --yes install g++

echo "IEEE1394 ================================================================"
echo " ..."
sleep 1
sudo apt-get --yes install libraw1394-dev
cd ../libdc1394-2.0.3/
./configure
make
sudo make install
sudo ldconfig
cd ../candiii

echo "remake =================================================================="
./remake 

echo "done ===================================================================="
echo

