#!/bin/bash

if test -f transform/GenPoints/getsurf.c ; then
	# The surface matrix has been compiled successfully
	echo "(The surface matrix was already compiled)"
else
	# Compile the surface matrix
	echo "Compiling the surface matrix..."
	cd transform/GenPoints/ ; make ; ./genpoints ; cd ../..
fi

echo "Creating: candi.pro"
shopt -s extglob
qmake-qt4 -project \
		-o candi.pro \
		CONFIG+=debug \
		LIBS+="-L /usr/local/lib -lplayercore -lltdl -lpthread -lplayerc++ -lplayerc -lm -lplayerxdr -lplayererror" \
		LIBS+="-lGL" \
		LIBS+="-lglut" \
		INCLUDEPATH+="/usr/local/include/player-2.0/" \
	-after \
		DEPENDPATH-="transform/GenPoints" \
		DEPENDPATH-="transform/c_code" \
		`./remove-sources transform/c_code/*.+(c|cc|cpp|h)` \
		SOURCES-="transform/GenPoints/genpoints.c" \
		SOURCES-="transform/GenPoints/genpoints_old.c"

echo "Creating: Makefile"
qmake-qt4 -makefile

echo "Type 'make' to compile everything"
