all:
	@# Create .o files
	libtool --mode=compile g++ -c `pkg-config --cflags playercore` -I. *.cc
	libtool --mode=compile gcc -c `pkg-config --cflags playercore` -I. *.c
	
	@# Create .a, .so, .la files
	libtool --mode=link g++ -shared `pkg-config --libs playercore` $(LIBS) *.lo -o libimageseqbmpplugin.a
	libtool --mode=link g++ -shared `pkg-config --libs playercore` $(LIBS) *.lo -o libimageseqbmpplugin.so
	libtool --mode=link g++ -shared `pkg-config --libs playercore` $(LIBS) *.lo -o libimageseqbmpplugin.la
	
clean:
	-rm *.o *.a *.dylib *.la *.lo
