  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # effort Controllers ---------------------------------------
  left_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_axle
  right_wheel_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_axle

  # shock controllers ----------------------------------------
  left_wheel_shock_controller:
    joint: left_drive_shock
    type: effort_controllers/JointPositionController
    pid: {p: 10000, i: 0.0, d: 20}
  right_wheel_shock_controller:
    joint: right_drive_shock
    type: effort_controllers/JointPositionController
    pid: {p: 10000, i: 0.0, d: 20}
