# Configuration values for our OpenCV nodes tuned for a GAZEBO SIMULATION
config:

  # Pothole Detector configuration values
  pothole:

    # Radii for hough circle detector
    minRadius: 10
    maxRadius: 50

    # Radius for averaging pixels in a circle around the center
    whiteSampleRadius: 5

    # Size for filtering out contours that are too small
    contourSizeThreshold: 100

    # Adaptive thresholding of colors to filter out non-potholes
    blueAdaptiveThreshold: 75
    greenAdaptiveThreshold: 40
    redAdaptiveThreshold: 20

  # Line dectector configuration values
  line:

    # Canny edge detector thresholds
    cannyThresh: 65
    ratio: 2

    # HoughLinesP tunable values
    houghThreshold: 60
    houghMinLineLength: 35
    houghMaxLineGap: 10

    # The maximum forward distance from the robot to plot points in meters
    maxDistance: 8

    outputLineSpacing: 1
